version: 0.2

env:
  parameter-store:
    DOCKER_CRED_USR: /node-js-app/docker-cred/username
    DOCKER_CRED_PSW: /node-js-app/docker-cred/password
    DOCKER_REGISTRY_URL: /node-js-app/docker-registry-url
phases:
  install:
    runtime-versions:
      nodejs: 20.13.0
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building docker image..."
      - docker build -t "$DOCKER_CRED_USR/nodejs-app:latest" .
      - echo "Pushing docker image..."
      - echo "$DOCKER_CRED_PSW" | docker login -u "$DOCKER_CRED_USR" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker push "$DOCKER_CRED_USR/nodejs-app:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"
